name: "Build Frontend Firebase Functions"
on:
  push:
  workflow_dispatch:
jobs:
  upload:
    runs-on: nix
    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: nix --accept-flake-config build '.#frontend-functions'
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: frontend-functions
          path: |
            ./result/**/*
            ./result/*
